# Generated by Django 4.2.2 on 2023-12-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petstore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122, null=True)),
                ('line', models.CharField(max_length=122, null=True)),
                ('desc', models.TextField(null=True)),
                ('img1', models.TextField(null=True)),
                ('img2', models.TextField(null=True)),
                ('img3', models.TextField(null=True)),
            ],
        ),
    ]
