# Generated by Django 4.2.2 on 2023-12-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstore',
            name='price',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
