# Generated by Django 4.2.2 on 2024-01-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_buy_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='pet_id',
            field=models.IntegerField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pet_id',
            field=models.IntegerField(max_length=122, null=True),
        ),
    ]
